
## -------------------------------------
## Study Information
## -------------------------------------

author: 'Hoang Dong Nguyen'
study_name: 'World Bank Dataset'
kaggle_link: "https://www.kaggle.com/datasets/bhadramohit/world-bank-dataset?resource=download"


## -------------------------------------
## Parameters
## -------------------------------------

## path of the input data
input_data_directory: 'data'

## output directory
output_directory: 'results'

